#!/usr/bin/env python

import argh
import yaml


def main(user_profile_filepath, device_id):
    with open(user_profile_filepath) as f:
        profiles = yaml.load(f)

    for username, profile in profiles.iteritems():
        if profile['device_id'] == device_id:
            print _env_str_generator(username, profile['rk_token'])
            return

    raise Exception(
        'No user found for %s in profile file %s'
        % (device_id, user_profile_filepath))


def _env_str_generator(username, rk_token):
    return 'export RK_USER=%s; export RK_TOKEN=%s' % (username, rk_token)


if __name__ == '__main__':
    argh.dispatch_command(main)
